### ISSUE TITLE
1.4.5 causes error

### ISSUE THREAD

**Issue by FooleanBool** [imanghafoori1/laravel-widgetize#2]
I installed this today and by following your insructions here on github, got a widget produced and working. However after a composer update, I received:

```
FatalErrorException in TopUsersWidget.php line 10:
Access level to App\Widgets\TopUsersWidget::$template must be public (as in class Imanghafoori\Widgets\BaseWidget)
```

Downgrading to 1.4.4 removed the error.
Changing the variable types to public removes this error but leads to another.

https://github.com/zigstum/laracasts-forum-widgets

**Comment by imanghafoori1** [comment]
Thank you for reporting the bug.
It is fixed in 1.4.6
But anyway you have to change all the protected properties to public on your widgets.
due to  structural changes on the base widget class.

**Comment by imanghafoori1** [comment]
Thank you for providing the sample app you are working on.
I like to put the link of your repo on the readme file of the project. If you agree

**Comment by FooleanBool** [comment]
Good work on this. Changed all protected to public and no breakage on 1.4.6.
You are welcome to link to the sample app if it helps.
Thanks :)
