### ISSUE TITLE
cannot generate widget using artisan

### ISSUE THREAD

**Issue by ParkNoBreak** [imanghafoori1/laravel-widgetize#33]
PHP Fatal error:  Call to undefined method Imanghafoori\Widgets\WidgetGenerator:
:qualifyClass() in E:\XAMPP\PHP56\htdocs\mb\vendor\imanghafoori\laravel-widgetiz
e\src\WidgetGenerator.php on line 131

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Imanghafoori\Widgets\WidgetGenerator::qualifyClass
  ()

E:\XAMPP\PHP56\htdocs\mb>php artisan make:widget MySexyWidget
PHP Fatal error:  Call to undefined method Imanghafoori\Widgets\WidgetGenerator:
:qualifyClass() in E:\XAMPP\PHP56\htdocs\mb\vendor\imanghafoori\laravel-widgetiz
e\src\WidgetGenerator.php on line 131

**Comment by imanghafoori1** [comment]
@kimcilcoin 
Which version of laravel ?
it seems your laravel version is something old.

**Comment by ParkNoBreak** [comment]
im using laravel 5.2

and already done by adding private method on WidgetGenerator.php

private function qualifyClass($class='')
    {
        return 'App\\Widgets\\'. str_replace('/', '\\', $class);
    }

**Comment by imanghafoori1** [comment]
Thank you for reporting this issue.
But because of laravel api changes the command line feature does not support version 5.2 and below.
Anyway you should be ok with the main functionality of the package.
