### ISSUE TITLE
Internet explorer directives Issue

### ISSUE THREAD

**Issue by lhoucinecherif** [imanghafoori1/laravel-widgetize#36]
Hi
And thank you for this awsome package.
I have some issue  preserving IE Directives like :  `<!--[if IE 9]><video style="display: none;"><![endif]--> `
the widget output  remove completely the content and write  : `<>` instead.

on every HTML comment we have `<>` instead of the comment `<!-- ... --> `, 

HTML comment are not visible , but `<>`  were rendred on the browser page !!

==========

-  Laravel version : 5.5 
-  Laravel-widgetize : 1.8
-  PHP : 7.1.14
-  Apache : 2.4.27

==========

Thank you

**Comment by imanghafoori1** [comment]
You should disable the minification of course (because we remove HTML comments while we minify the widget's output.)
or you may put the IE stuff some where out of the widget.

**Comment by lhoucinecherif** [comment]
Thank you :+1:
