### ISSUE TITLE
مشکل در لایبرری

### ISSUE THREAD

**Issue by falahatiali** [imanghafoori1/laravel-widgetize#37]
سلام خدمت شما 
آقای غفوری عزیز ما به یک مشکلی برخوردیم در این ماژول
اون هم این هست که دیتایی که در کنترلر تولید میشه و وارد فایل 
blade
میشه رو نمیشناسه
مثلا ما دوتا فیلد داریم بنام 
about , posts
اینها رو نمیشناسه 
بلکه فیلدی که داخل 

blade

میاد 
data 
هست

و این دوتا متغیر داخل 
data
قرار دارند.
مشکلش از کدوم قسمته ؟

**Comment by imanghafoori1** [comment]
سلام
اسکرین شات از کدتون لطفا

**Comment by falahatiali** [comment]
کدوم قسمت کد ؟

**Comment by falahatiali** [comment]
```
class Campaigns
{
    public function data($list = false, $full = false, $cid = 0)
    {
       
        $return = [
            'about' => \App\Models\Page::firstOrNew(['cid' => 1]),
            'campaigns' => \App\Models\Campaign::get(),
        ];

        return $return;

    }

 
}
```

**Comment by falahatiali** [comment]
الان اینجا دوتا متغیر رو نمیشناسه
about , campaign
فقط
data
رو میشناسه

**Comment by imanghafoori1** [comment]
$data['about']

$data['campaigns']
  
رو نگاه کنید

**Comment by falahatiali** [comment]
این دوتا رو میشناسه ولی این پروژه قبلا کار میکرد با مقادیر مربوط به خودش
الان اینجوری شده
قبلا نوشته شده و کار میکرده

**Comment by imanghafoori1** [comment]
آپدیت کردید؟
چون دقیقا یادم نیست تو ورژن های جدیدش چه تغییراتی اعمال کرده بودم

**Comment by falahatiali** [comment]
نه من فقط پروژه رو دریافت کردم منتها قبلا روی 
php5
توسعه داده شده بود ولی من روی سیستمم با استفاده از 
php7.2
بالا اوردمش

**Comment by imanghafoori1** [comment]
اجازه بده من خاطرم نیست کدی که نوشتم دقیقا چی بوده.
باید نگاه کنم
ضمنا یه اکرین شات از فایل blade هم لازم دارم

**Comment by falahatiali** [comment]
دست شما درد نکنه خیلی ممنون 
اسکرین شات رو براتون میفرستم

**Comment by imanghafoori1** [comment]
الان یادم اومد.
این حالت برای ورژن های قدیمی تر بود
و بعدا تغییر کرد و شد این حالتی که الان هست.
شما باید یه کم کدتون رو تغییر بدید

ولی من حدس میزنم که ورژن پکیج آپدیت شده باشه.
به هر حال ورژن فعلی ش که این طوری باید کار کنه

**Comment by falahatiali** [comment]
"imanghafoori/laravel-widgetize": "1.*",

**Comment by falahatiali** [comment]
ورژن پکیج اسن هست

**Comment by falahatiali** [comment]
![capture](https://user-images.githubusercontent.com/17930523/50538037-f3c37000-0b7d-11e9-9aca-d5bcfff45d1f.PNG)

**Comment by imanghafoori1** [comment]
کدتون رو بی زحمت با خالت جدید مطابق بدید. نباید کار سختی باشه.
خیلی ساده س.
<؟php
extract($data);
<?

رو بالای فایل بلید اضافه کنید. باید کار کنه
