### ISSUE TITLE
I need something like WidgetWhen(Condition,WidgetView)

### ISSUE THREAD

**Issue by mma56k** [imanghafoori1/laravel-widgetize#41]

**Comment by Yahav** [comment]
Ohh, that's a really good idea 👍

**Comment by Yahav** [comment]
Perhaps something like this:

> Blade::directive('widgetWhen', function ($conditionResult, $expression) use ($omitParenthesis) {
>     if ($conditionResult===true) {
>     $expression = $omitParenthesis ? $expression : "($expression)";
>             return "<?php echo app(\\Imanghafoori\\Widgets\\Utils\\WidgetRenderer::class)->renderWidget{$expression}; ?>";
>     }
> else {
>     return "";
> }
>  });

**Comment by mma56k** [comment]
thanks a lot.
but i suggest something more simple
to reduce lines of code

**Comment by imanghafoori1** [comment]
stay away from it
