### ISSUE TITLE
asset() helper return server ip instead of domain name

### ISSUE THREAD

**Issue by payamomrani** [imanghafoori1/laravel-widgetize#59]
Hi iman
i use asset helper in widget view for route of my images
when cache is clear and widgetize rebuild , route change from my domain to my server ip
after than when i run php artisan cache:clear it ok and  set domain name
how can i fix this ?

thank you

**Comment by imanghafoori1** [comment]
Hi Payman, Please give me a better explanation of your problem, so I can help you
