### ISSUE TITLE
Seems to break Debugbar after composer require

### ISSUE THREAD

**Issue by jordonbaade** [imanghafoori1/laravel-widgetize#6]
Working locally on a new project and wanted to test this out.  Unfortunately as soon as I install it with composer require it breaks https://github.com/barryvdh/laravel-debugbar/ - I don't even have to add the ServiceProvider.

Steps to reproduce:

1. Using Laravel Valet (I am at least),
2. Install new Laravel project (I'm using 5.4.26),
3. ```composer require barryvdh/laravel-debugbar --dev```,
4. Add debugbar ServceProvider to config/app.php,
5. Visit '/' to see debug bar,
6. ```composer require imanghafoori1/laravel-widgetize```,
7. Visit '/' to see debug bar broken
8. ```composer remove imanghafoori1/laravel-widgetize```
9. Visit '/' to see debug bar working again.

Error received from JS console:
```Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://temp1.dev/_debugbar/assets/stylesheets?v=1496339168".```

![image](https://user-images.githubusercontent.com/840932/27158444-fce1328a-5134-11e7-8f78-87c52f3bca66.png)

**Comment by imanghafoori1** [comment]
I do not think that there is anything I can fix.
Because if the package's service provider is not added, laravel not  know any thing about the installed package.
It seems that a css file related to debugbar package is served as an text/html file so the browser is confused about that and is not able to parse and apply the proper styles to debugbar's html.

Have you tried debugbar alongside other packges (other than widgetize) ?

**Comment by jordonbaade** [comment]
Yeah, not sure.  I thought it was a weird one.

The thing is that css file is served as text/html only after requiring your package, without the package it is served as a stylesheet and works.  Do you perhaps have some catch all routes,  or anything loaded via auto loading that could be doing it?

I use debugbar with every Laravel project.  This project has many other packages along with it, I actually had to install debugbar and each package in the project into a temp project one by one to finally find that it was  caused by requiring your package.

**Comment by imanghafoori1** [comment]
- Do you perhaps have some catch all routes?
> Without adding the service provider, Even if there is a catch all route, it is not able to step in and cause any problem.


> I performed the mentioned steps to reproduce the problem.
(installed a fresh copy of laravel 5.4.23
added the composer require barryvdh/laravel-debugbar --dev and etc...)
But everything is working for me.
except I am not using the laravel valet.
I tested it with xampp and php artisan serve

**Comment by jordonbaade** [comment]
Weird!  Thanks for giving it a go, I'll try to play around with it and valet to see if I can fix it.

**Comment by imanghafoori1** [comment]
Anyway I am currently using debugbar and widgetize together on my own project with laravel 5.1 and have no problem.
I wish you enjoy my package.
