### ISSUE TITLE
Not working in Laravel 10

### ISSUE THREAD

**Issue by RandUser123sa** [imanghafoori1/laravel-widgetize#83]
The widgetize not working in Laravel 10.0

**Comment by imanghafoori1** [comment]
Could you please provide the error message you get?

**Comment by RandUser123sa** [comment]
Problem 1
    - imanghafoori/laravel-widgetize v2.2.46 requires php ^7.1.3|7.2.*|7.3.*|7.4.* -> your php version (8.1.17; overridden via config.platform, actual: 8.1.25) does not satisfy that requirement.
    - imanghafoori/laravel-widgetize v2.2.47 requires laravel/framework ~5.1|6.*|7.*|8.* -> found laravel/framework[v5.1.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^10.8).
    - imanghafoori/laravel-widgetize v2.2.48 requires laravel/framework ~5.1|6.*|7.*|8.*|9.* -> found laravel/framework[v5.1.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.8).
    - Root composer.json requires imanghafoori/laravel-widgetize ^2.0 -> satisfiable by imanghafoori/laravel-widgetize[v2.2.46, v2.2.47, v2.2.48].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by imanghafoori1** [comment]
I have forgotten to tag the new release. You can now install it.
